### ISSUE TITLE
Prompt for passwords for encrypted keys

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-ui#1]
![image](https://user-images.githubusercontent.com/172531/31367128-be876ee4-ada7-11e7-9216-b9bb6cebd1e3.png)

`basecli` generates encrypted addresses. We need some way of using this for the UI with perhaps a popup modal.

**Comment by adrianbrink** [comment]
This is linked to: https://github.com/tendermint/go-crypto/pull/38

**Comment by nylira** [comment]
Don't think this is an issue anymore since we're creating new keypairs in the UI.
