### ISSUE TITLE
Simplify NiAppMenu

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-ui#128]
With the recent removal of viewing lists of delegators, the receive page, and the nomination page, the sidebar seems overloaded with section titles. The page that do exist are a little empty and the content seems too thinly spread out when they should be shown together.

## Current Navigation

* **WALLET**
  * Balances
  * Send
  * Transactions
* **GOVERN**
  * Proposals
* **STAKE**
  * Delegate
* **MONITOR**
  * Blockchain
  * Validators

## Proposed Navigation
I want to propose a primary app navigation with just four buttons.

### 1. Wallet

The wallet page shows your primary address and balances on the top of the page. Below that is a list of most recent 20-30 transactions.

*Page Nav*: [Index], Transaction History (this page is a longer version of the recent transactions list)

*Page Actions*: Send Tokens (pressing "Send Tokens" will create a modal popup allowing you to fill in details about the tx).

### 2. Govern

The govern page shows a list of current proposals.

*Page Nav*: [Index], Finished Proposals (finished proposals are proposals that have already either been accepted or rejected)

### 3. Stake
The delegation game is not a thing anymore. The most important thing users will want to see on the Stake page is their current basket of validators (it's sort of like an index fund).

*Page Nav*: [Index], Edit Basket of Validators (this page shows a detailed, filterable list of all current validators)

### 4. Monitor
The monitor page shows important blockchain details at the top, and then a list of validators below that. The list of validators can be sorted and filtered.

*Page Nav*: [Index], Search Blockchain (this page will let you search for transactions, blocks, etc. in the cosmos network)

Thoughts on this?

**Comment by jolesbi** [comment]
@nylira do you still want to discuss this / change the app architecture?

**Comment by nylira** [comment]
Yeah, let's change the navigation, and make everything nouns. My updated proposal:

* Balances - actions: view/filter balance, view/filter transactions, create new sendtx
* Proposals - actions: view proposals, filter proposals, create proposal
* Delegates - actions: view delegates, filter delegates, bond to delegates
* Monitor - actions: view status of the network, search for tx
* User - actions: view profile, edit account settings, change account

There is merit to making a Transactions page as a main navigation item. I think it can cause confusion though. Let's say you're a user and you want to send some tokens (aka create a transaction). Would you go to the Balances page or the Transactions page? It makes the most sense to merge these pages.

**Comment by nylira** [comment]
It would be great to have 4 custom icons, one for each page of the app.

For the default sign in page, I have some thoughts on this:

* For a fresh user experience, signing in onto the Monitor page makes the most sense because there will be a wow factor to seeing the nodes and performance statistics of the network
* For a returning user, they probably won't care as much about the netmon -- as long as it's running for them, that's the important part. Most regular users will want to go to the Balances page.
* The solution for this: save the currently opened page to localstorage on exit and restore the page when they open the app again.

**Comment by jolesbi** [comment]
upon reviewing this ticket again, this is a huge task... unless i'm misunderstanding. @nylira i'll make a wireframe tomorrow to make sure we're on the same page.

**Comment by nylira** [comment]
Not everything has to be done in one PR. I think the important parts are

* moving the Send page to a modal on the Balances page
* moving the transactions data to the Balances page
* removing the section headings in the navigation

The other stuff (icons, restore page on quit, anything else?) can be done later.

**Comment by jolesbi** [comment]
> moving the Send page to a modal on the Balances page

i'm into this. but i'd also be ok with adding a "send" button to the balances page which takes the user to the send page with the correct denomination pre-selected... i think this would be a good first step.

> removing the section headings in the navigation

just to clarify, do you mean the sidebar AND the mobile menu? do you imagine there still being a space to separate these links or just one uniform list?

**Comment by nylira** [comment]
@jolesbi
Yes, send buttons next to each coin balance would be awesome.

 And yes, remove the section headings in the sidebar and the mobile menu. I've always thought they were information overload. Especially now that we're cutting down on the number of links.
