### ISSUE TITLE
Validator Profile

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#132]
As a user
I want to be able to see details for validators
so that I can make sophisticated decisions on delegating my atoms.

AC (profile shows):
- [x] Validator Name
- [x] Validator Website
- [x] Validator Description (this can hold links to external ressources like an audit)
- [x] atoms self-bonded
- [x] atoms delegated to them
- [x] commission rate
  -https://github.com/cosmos/gaia/blob/proposals/spec.md#fee-pool-commission
- [x] how long they have been validator
- [x] max commission rate (the rate that it will never go higher than)
- [x] max commission increase rate (the max amount it can increase over time)

**Comment by faboweb** [comment]
Current state:
![image](https://user-images.githubusercontent.com/5869273/33314727-d38a9b42-d42e-11e7-9732-c2cf8a5b192c.png)

**Comment by faboweb** [comment]
I assume shares equal "atoms delegated to them"? This isn't very clear to me.

**Comment by jolesbi** [comment]
@faboweb that's a good point. i'd like to see more tooltips available with small definitions / descriptions. there is a lot of vocabulary that can be overwhelming / difficult to understand.

**Comment by jolesbi** [comment]
some things missing from the screenshot include ...

- max commission rate (the rate that it will never go higher than)
- max commission increase rate (the max amount it can increase over time)

@rigelrozanski is it possible to display the denomination of the fee shares?

**Comment by jolesbi** [comment]
next release will include `moniker` for validators.

let's make sure we include this field in the UI :)

**Comment by nylira** [comment]
@jolesbi who sets the max commission rate and max commission increase rate? And can the validator make changes to their profile? If they can make changes--for example, fix a typo on their description or website url--what prevents them from changing their max commission rate and increase rate?

**Comment by nylira** [comment]
We have another Validator Profile page on the Network Monitor section of the app.

<img width="778" alt="screen shot 2017-11-30 at 11 50 48 am" src="https://user-images.githubusercontent.com/172531/33410700-cf34eca4-d5c4-11e7-8ab3-2a3963543646.png">

How can we reconcile the differences between the two pages?

**Comment by nylira** [comment]
The reason there are two Validator Profile pages is an interesting historical footnote. About three months ago, we were focused on releasing a portion of the Cosmos UI called the "Delegation Game" . Along with the UI we would release the `gaia` network which would have included staking functionality. The Delegation Game had limited functionality - you could not send or receive Atoms. You could only view a list of validator candidates and then delegate your Atoms to them. Fast forward to November, we still don't have the UI out yet, and `gaia` is only getting its staking functionality now.

From my current understanding (@mappum correct me if I'm wrong), we are no longer having a `Delegation Game` before mainnet release. That means we no longer need any references to Validator Candidates throughout the app. There will be validators and delegators. To be a validator, you simply need to learn how to use the CLI to submit your details to the network. You no longer need to hold atoms to be a validator. Atom holders who use Cosmos UI can choose to delegate to zero or more validators.

What does this mean for our two Validator Profile pages? Without the concept of Candidates, both of the Validator Profile pages are going to be near identical. And since the Network Monitor Validators page has no functionality other than displaying information, we should delete these pages.

**Comment by jolesbi** [comment]
woah. very interesting.

max rate and max increase rate are set by validators. they are basically the terms that a delegator would be interested in knowing. i believe that these two data points cannot be changed by any means. if a validator wants to change these terms they basically need to create a new validator profile.

my understanding is that we don’t want validators to rely too heavily on the UI but I think it would be nice for validators to be able to edit their profiles in the UI. 

i’m not sure so we’ll need confirmation on this but i don’t think we doing the delegation game anymore - but validators do in fact have at least one have atom to become a validator.

re: two validator pages. we should have one that contains all the info from both. 

would be good for@mappum on this.

candidates are definitely still a thing but my understanding is that they are validators who aren’t in the top 100 yet.

**Comment by mappum** [comment]
That's right, there still is a distinction between validators and candidates, and the validators are just the top 100 candidates with the most Atoms bonded.

>re: two validator pages. we should have one that contains all the info from both. ideally, all links to the validator profile page would go to the same profile component / page.

That sounds like it makes the most sense, candidates who are not validators should just not have certain fields on their profile like Earn Rate, Voting Power, etc., but should still have a Website, etc. Probably makes sense to have a field that explicitly explains their standing ("This candidate is a validator").

**Comment by rigelrozanski** [comment]
@jolesbi 
>max rate and max increase rate are set by validators. they are basically the terms that a delegator would be interested in knowing. i believe that these two data points cannot be changed by any means. if a validator wants to change these terms they basically need to create a new validator profile, so i guess we should display these fields but they need to be disabled.

Partially correct, the validator can choose to further restrict their terms, but not the opposite. They must re-create their candidacy if they want more lax terms.
>my understanding is that we don’t want validators to rely too heavily on the UI but I think it would be nice for validators to be able to edit their profiles. i would also understand why we would want this to be readonly. what do you think from a ux perspective @nylira ?

Validators do not need a UI they can use the CLI - shouldn't focus on this I don't think - more to maintain.
>i’m not sure so we’ll need confirmation on this but — i don’t think we doing the delegation game anymore — but validators still need to have at least one atom to become a validator. having one atom is enough to receive tokens from delegators.

Every validator needs > 0 atoms (a fraction of an atom is okay)
>candidates are definitely still a thing but my understanding is that they are validators who aren’t in the top 100 yet. also, validators / candidate validators are a dynamic thing. sometimes validators will fluctuate between being validators and being candidates based on where they rank in the list of 100. @rigelrozanski should confirm the above info.

correct

**Comment by jolesbi** [comment]
should we close this ticket?

**Comment by nylira** [comment]
Yeah, let's close it. When we have more issues with the profile we'll open a new one.

**Comment by faboweb** [comment]
Does the validator profile actually show real data? If not I would either reopen this ticket, unchecking all the AC that do not show real data or create a new ticket that handle all the real data. @jolesbi @nylira

**Comment by nylira** [comment]
I'll make a new ticket for this. Good point @faboweb

**Comment by faboweb** [comment]
Thx Peng
