### ISSUE TITLE
package.json is missing vue

### ISSUE THREAD

**Issue by huashengzhang** [cosmos/cosmos-ui#140]
package.json is missing vue

**Comment by faboweb** [comment]
It is in the nested package.json. https://github.com/cosmos/cosmos-ui/blob/develop/app/package.json#L27

Do you get an error at some point?

**Comment by huashengzhang** [comment]
run：yarn run uionly or npm run testnet
bug：
![qq 20171130134116](https://user-images.githubusercontent.com/31681100/33415849-54f1e964-d5d4-11e7-8cb7-89cc77e11d60.png)

run：npm i vue -s, bug solved

**Comment by faboweb** [comment]
The issue is the template compiler is updated away from the vue package.
