### ISSUE TITLE
form validation is INTENSE

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#151]
i'm curious to hear everyone's thoughts on this. basically, the validation on our form fields kicks in right away. so if you try to send someone some tokens and you type 1 character the form turns red and you get an error. it can feel quite aggressive. as an alternative, i'll propose a couple options.

1. validate form on submit
2. add a sensible delay on `keyup` to the validation

what do you guys think about this?

**Comment by nylira** [comment]
This is a bug with our code. Validation shouldn't be kicking in until submit is hit for the first time.
