### ISSUE TITLE
Mock-server times out for /keys

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#159]
OS Ubuntu

If going into production mode, everything works fine.

**Comment by faboweb** [comment]
Happens if there are no keys.

**Comment by faboweb** [comment]
Requesting the key once from the cmd line `curl http://localhost:8999/keys` enables the proxy...

**Comment by mappum** [comment]
@faboweb Are you still having this issue?

**Comment by faboweb** [comment]
Still the case.
