### ISSUE TITLE
audit colours for accessibility and contrast ratio

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#167]
recommend we use lea verou's tool to establish a WCAG 2.0 compliant colour scheme (DARK-THEME FO LYFE) 🎨 

i'll make a PR with the closest colours from `variables.styl` that pass the accessibility contrast check at any font-size on our background colour. 

http://leaverou.github.io/contrast-ratio/

**Comment by jolesbi** [comment]
@nylira 👍

**Comment by nylira** [comment]
Sounds good! Look forward to seeing it.

**Comment by jolesbi** [comment]
<img width="917" alt="screen shot 2017-12-07 at 2 55 18 pm" src="https://user-images.githubusercontent.com/6021933/33742842-02df7fa2-db5f-11e7-9423-766440d42722.png">
<img width="909" alt="screen shot 2017-12-07 at 2 49 10 pm" src="https://user-images.githubusercontent.com/6021933/33742843-02f4f1f2-db5f-11e7-983d-50f559dce5fa.png">
<img width="962" alt="screen shot 2017-12-07 at 2 42 19 pm" src="https://user-images.githubusercontent.com/6021933/33742845-0306d908-db5f-11e7-8a8c-4ae6c5d58f79.png">
<img width="970" alt="screen shot 2017-12-07 at 2 41 01 pm" src="https://user-images.githubusercontent.com/6021933/33742846-031b5d60-db5f-11e7-8eee-2ee4d12d8fc2.png">
<img width="936" alt="screen shot 2017-12-07 at 2 40 15 pm" src="https://user-images.githubusercontent.com/6021933/33742847-032c41fc-db5f-11e7-9afc-82f5ce3bdbfc.png">
<img width="886" alt="screen shot 2017-12-07 at 2 39 32 pm" src="https://user-images.githubusercontent.com/6021933/33742848-034072e4-db5f-11e7-9a48-5b5c4ad64f41.png">

**Comment by faboweb** [comment]
Well done :)
