### ISSUE TITLE
it would be nice if the back button was on the left side instead of the right

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#180]
what do you think @nylira ?

**Comment by nylira** [comment]
I think that makes sense.

**Comment by jolesbi** [comment]
where should we put it? 😕

**Comment by nylira** [comment]
Putting it to the left of the page title screws up the nice layout of the page header area.

I propose adding a text label to the back arrow, make it small, and then putting it on top of the page title. E.g.

> 
> <- Validators
> **FABIAN-THE -VALIDATOR**

**Comment by jolesbi** [comment]
good idea! but i think we'll have to increase the logo spacing / height i think.

**Comment by jolesbi** [comment]
@nylira my mind has changed about this ticket. i am totally comfortable with the back button in the toolbar on the right. it seems to me that we don't have any routes that are more than one or two deep anyways, so using "back" will be just as easy clicking the route in the sidebar. 

that being said, i will make sure it's on every page and in the same place. i think for now, this should be ok.

👍 😆 🙃
