### ISSUE TITLE
toolbar can stay in the topbar on mobile

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#181]
@nylira i think it would be better to leave the toolbar in the top bar on mobile. this will provide a more consistent experience.

**Comment by nylira** [comment]
I think I like them where they are, because there is a fixed top bar already. The toolbar is fixed to the page also, and if we have two fixed bars at the top of the page it'll feel very top heavy.

**Comment by jolesbi** [comment]
cool. let's close this for now.

**Comment by jolesbi** [comment]
hmmm. ok take a look at the screenshot in the PR and let me know what you think.
