### ISSUE TITLE
Wallet Balances

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#20]
As a user
I want to have an overview of my balances in the cosmos network
so that I have easy access to the knowledge of my values/tokens in the network.

AC:
- [x] The user can see the balance for a specified account
- [ ] The user can see the amount of bonded atoms

**Comment by faboweb** [comment]
We ignore bonded atoms for now.

**Comment by jolesbi** [comment]
the wallet balance won't included bonded atoms since bonded atoms actually leave the user's account when they are staked 👌
