### ISSUE TITLE
Improve button design

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-ui#203]
We need a good primary button design with (most likely) a full color background using our `link` color.

We need an danger! button design using the `danger` color for serious actions like deleting an account.

The default button height of 2rem looks too small on desktop, consider increasing button height to 2.5rem by default?

- [x] primary button color
- [x] success button color
- [x] warning button color
- [x] danger button color
- [x] fix button overflow issue

**Comment by jolesbi** [comment]
i agree 100%!!!

**Comment by faboweb** [comment]
Sounds good.

**Comment by nylira** [comment]
I'm not a fan of the button currently:

<img width="143" alt="screen shot 2018-01-15 at 12 52 22 pm" src="https://user-images.githubusercontent.com/172531/34927675-f3fdd7b0-f9f2-11e7-8546-04d70e1b4087.png">

The background and outer border look incredibly washed out. Let's improve this.

**Comment by jolesbi** [comment]
please improve! just wanted to make sure the primary was there.
