### ISSUE TITLE
if the node that the UI is connected to goes down

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#204]
we should handle this scenario so you don't have to restart the UI to reconnect

**Comment by faboweb** [comment]
I specified the wrong issue in #210

**Comment by gamarin2** [comment]
Isn't this automatic in the light-client? Like if full-node goes down, you start peer-discovery again?

**Comment by jolesbi** [comment]
that would be nice

**Comment by jolesbi** [comment]
closed by #283
