### ISSUE TITLE
version in "about section" of release 0.2.0 is wrong

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#221]
<img width="404" alt="screen shot 2017-12-11 at 9 39 31 am" src="https://user-images.githubusercontent.com/6021933/33845138-4a19ebfa-de57-11e7-8675-594751ee657a.png">

**Comment by jolesbi** [comment]
https://electronjs.org/docs/development/releasing
https://github.com/electron/electron/commit/78ec1b8f89b3886b856377a1756a51617bc33f5a

**Comment by faboweb** [comment]
Note: Those links are about releasing the electron-framework not an electron application.

**Comment by nylira** [comment]
This seems like it's no longer a thing with `electron-builder`. This is the only menu we have right now:

<img width="154" alt="screen shot 2018-01-10 at 2 21 03 pm" src="https://user-images.githubusercontent.com/172531/34756931-8414ac7e-f611-11e7-828a-03375ce2db91.png">

**Comment by jolesbi** [comment]
i think it's worth having version information available.

**Comment by mappum** [comment]
Closing this issue since now the internal version number is correct, and we don't show the about dialog right now. (Opened #348 instead)
