### ISSUE TITLE
Delegation

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#24]
As a user
I want to be able to delegate my atoms to a validator
so that I can support the network in validation and earn commission.

AC:
- [x] User is able to view all the validators
- [x] User is able to view the profile of each validator
  - [ ] Validator Name
  - [ ] Validator Website
  - [ ] Validator Description (this can hold links to external ressources like an audit)
  - [ ] atoms self-bonded
  - [ ] atoms delegated to them
  - [ ] commission rate
    - https://github.com/cosmos/gaia/blob/proposals/spec.md#fee-pool-commission
  - [ ] how long they have been validator
- [x] User is able to bond a certain amount of atoms to a selected validator
- [ ] User is able to unbond atoms off a selected validator
- [ ] User is able to see all the validators he has bonded atoms with (and the amount of atoms per validator)
- [ ] User is able to see the amount of commission they have earned

Note:
- Does a user need to unbond all atoms at once or can he unbound partial amounts?

**Comment by faboweb** [comment]
Peng:
Important validator metrics for delegators to make an informed decision: 
* Indicators of validator's external audits
* trustworthiness of the auditor(s)
* indicators of past performance
  * validator uptime
  * voting history, etc.

**Comment by faboweb** [comment]
@nylira 
Do we have information about external audits in the system?
How is the trustworthiness of auditors measured?

**Comment by nylira** [comment]
External audits will be conducted by trusted third parties like @zmanian. We'll want to provide some sort of "seal of trust" or "verification badge" per third-party audit that the validator passes. The validator will be able to paste their unique verification code into their config files, and the Cosmos UI should show them to delegators. Ideally, we wouldn't want any atom holder to delegate atoms to a non-audited validator.

The trustworthiness of auditors is measured by their track record and domain knowledge in hardware security, availability, and protection against malicious attacks (DDoS etc). We'll definitely want to have several relatively trustable auditors. @zmanian would have more to say about this.

**Comment by faboweb** [comment]
Thx for the details :)

**Comment by jolesbi** [comment]
very interesting! @faboweb this seems "AC" worthy. a task which has not been accounted for yet.

**Comment by jolesbi** [comment]
waiting on @rigelrozanski ...

**Comment by rigelrozanski** [comment]
@faboweb what is the " auditing status of each validator"

**Comment by rigelrozanski** [comment]
@faboweb Also thanks for pinging me - I would have liked to be pinged in this one right from the get go!

**Comment by faboweb** [comment]
Thx goes to jordan I think. Thx for the clarification and feedback, we will try in the future to involve/ping people involved from the start.

> what is the auditing status?
By @gamarin:
I guess validators could pay independent firms to make an audit of their setup. We should not audit anything ourselves

> calculate what the commission gains are on the fly
How is the commission calculated?

> off chain 3rd party query for the active lists of all candidates or candidates which a delegator has bonded too
Let's consider this. I have the feeling that not being able to see where you (as a user of the light client) have bond is a bad idea.

**Comment by faboweb** [comment]
Let's assume for now that the audit status is self-provided by the validator and is reflected by a link to an off-chain resource.

**Comment by rigelrozanski** [comment]
@faboweb yes audits to happen off chain - can be linked in the desciption of a validator if they wish
>How is the commission calculated?

See the spec: https://github.com/cosmos/gaia/blob/proposals/spec.md
Validators get to choose their own commission

**Comment by zmanian** [comment]
When there are screenshots/mocks of delegation UI could someone post them to the issue?

**Comment by faboweb** [comment]
@zmanian will do!

**Comment by faboweb** [comment]
Open subtasks splittet out: #132  #133 #134 #135
