### ISSUE TITLE
deterministic, verifiable builds

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#245]
this is vert important. but can wait until next sprint.

JB:
> i'd like to hold off on implementing deterministic builds (with signed releases) until at least dec 28

Jae:
> as long as we don’t put blog posts out, and we put all the disclaimers, that sounds good.

related to #232 

@jaekwon

**Comment by mappum** [comment]
This issue should stay open until we can build the entire app bundles deterministically, so far it's just the Gaia binaries.

**Comment by jolesbi** [comment]
closed in favour of #342
