### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#25]
As a user
I want to be able use the wallet without obvious errors
so that I I don't feel frustrated using Cosmos.

AC:
- [x] Every release is tested for obvious errors -> CI
- [ ] 80% test coverage -> unit testing
- [ ] The critical functionalities are tested E2E via some automated browser tests

**Comment by faboweb** [comment]
Includes #3

**Comment by jolesbi** [comment]
- [x] unit tests for /wallet components are done.

closing this ticket in favour of #119 #120 #121 #122 #123 #124
