### ISSUE TITLE
fixed footer cuts of bottom row of index page

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#261]
<img width="1065" alt="screen shot 2017-12-19 at 4 08 58 pm" src="https://user-images.githubusercontent.com/6021933/34178947-ff2a00c2-e4d6-11e7-9039-64ad99b523d8.png">

**Comment by nylira** [comment]
I can't recreate this. Maybe it's been fixed in a PR?

![screen shot 2017-12-27 at 1 45 37 pm](https://user-images.githubusercontent.com/172531/34370977-4b21661a-eb0c-11e7-9459-63ede6f3c971.png)

**Comment by jolesbi** [comment]
yep. can't reproduce any more.
