### ISSUE TITLE
Balanced didn't be refreshed

### ISSUE THREAD

**Issue by suuuuwanzi** [cosmos/cosmos-ui#263]
I've signed in and used  address applyed 30 fermions in http://www.cosmosvalidators.com/.But the wallet balance didn't be refreshed .  I ‘ve pressed "refresh button" for many times.

**Comment by jolesbi** [comment]
@suuuuwanzi can you share some details about the version you are using? are you building the UI locally or are you using release 0.2.0? do you know which gaia version you are on?

**Comment by nylira** [comment]
@suuuuwanzi which operating system are you using?

**Comment by suuuuwanzi** [comment]
@nylira @jolesbi   ui from :   https://github.com/cosmos/cosmos-ui/releases    (download : cosmos-0.2.0-win.exe)     OS :Windows 7
I run a gaia-1 node on Server （Linux -Ubuntu LTS 14.04.3）   gaia-version :0.3.0

**Comment by faboweb** [comment]
HI @suuuuwanzi,
The windows version already runs on a newer testnet (gaia-2-dev). Check out the bottom left label in the app stating the network. http://www.cosmosvalidators.com only works with gaia-1. If you tell me your address I send you some fermions. 💸

**Comment by jolesbi** [comment]
@suuuuwanzi i'm going to close this and assume this was an issue about conflicting testnet versions. please let us know if you have any more trouble.

**Comment by suuuuwanzi** [comment]
@faboweb  oh,thank you so much .  ADDRESS：  2EC7099F334D3A41CD4AAA4490D857E57FD981ED

**Comment by mappum** [comment]
@suuuuwanzi Sent you some Fermions!
