### ISSUE TITLE
improve bonding UX

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#275]
from #133

**Comment by faboweb** [comment]
Current view:

![image](https://user-images.githubusercontent.com/5869273/34408822-46d6914c-ebc6-11e7-8653-baeeec353dac.png)
![image](https://user-images.githubusercontent.com/5869273/34408832-53bc67c4-ebc6-11e7-8ec4-5127924dedf8.png)
![image](https://user-images.githubusercontent.com/5869273/34408840-6456fdb0-ebc6-11e7-83de-d1771df99b6b.png)

**Comment by jolesbi** [comment]
- should delegates be selected by default?

**Comment by jolesbi** [comment]
closed by #331 and others related
