### ISSUE TITLE
footer broken on small screen

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#282]
![image](https://user-images.githubusercontent.com/5869273/34411290-2b14660e-ebd6-11e7-875b-3e91c763c23e.png)
![image](https://user-images.githubusercontent.com/5869273/34411320-419e1398-ebd6-11e7-9e91-db9a13fd6957.png)

* it doesn't show node connection
* it doesn't hide list items in background

**Comment by jolesbi** [comment]
@faboweb: (how) do we show connection on mobile?
