### ISSUE TITLE
Footer doesn't stick to bottom

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#289]
If there are no denominations, the footer stretches the whole panel.

- [ ] fix ni-page height / footer not being on bottom

![image](https://user-images.githubusercontent.com/5869273/34442113-47802d74-ecc0-11e7-9d9b-5c56b9bbe5d7.png)

**Comment by jolesbi** [comment]
"Connectivity" is also in the sidebar when on desktop

**Comment by nylira** [comment]
Alright guys, I can't recreate either of these issues.

When I set `wallet.balances` to empty, this is what I see:

<img width="591" alt="screen shot 2018-01-12 at 1 07 18 pm" src="https://user-images.githubusercontent.com/172531/34859456-9dab16bc-f799-11e7-95fd-3b436e2b5ca1.png">

Connectivity isn't in the sidebar for desktop:

<img width="782" alt="screen shot 2018-01-12 at 1 07 24 pm" src="https://user-images.githubusercontent.com/172531/34859462-a869bc66-f799-11e7-983e-dd6cede1f30a.png">

Connectivity does show up in the sidebar for mobile:

<img width="331" alt="screen shot 2018-01-12 at 1 08 46 pm" src="https://user-images.githubusercontent.com/172531/34859475-c0bd2fbe-f799-11e7-8c69-c0c3242427f0.png">
<img width="590" alt="screen shot 2018-01-12 at 1 08 41 pm" src="https://user-images.githubusercontent.com/172531/34859476-c0e2e722-f799-11e7-827b-6318bdfcda92.png">

**Comment by faboweb** [comment]
I also tested it and it appears to be fixed. Thx Peng for the very sophisticated test. :)

**Comment by jolesbi** [comment]
i believe this is an issue on the delegation page.

**Comment by nylira** [comment]
@jolesbi can you share a screenshot? Do you mean the `.fixed-button-bar` is not being fixed to the bottom of the page for mobile?

<img width="404" alt="screen shot 2018-01-15 at 12 57 28 pm" src="https://user-images.githubusercontent.com/172531/34927779-b3b46330-f9f3-11e7-9a5a-9f4b1f86133d.png">
