### ISSUE TITLE
Network Monitoring

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#29]
As a user
I want to be able to see the status of the blockchain network
So that [I can see if there are enough nodes to securely facilitate my transaction?]

AC:
- [ ] User is able to see the node up time for every node in the network for last [day, week, month, year?]
- [ ] User is able to see the amount of currently active node?
- [ ] ~The network monitor is accessible from outside as a standalone website~
- [x] The network monitor is accessible from inside of the wallet

Notes:
- What is the value proposition?

**Comment by jolesbi** [comment]
from Thompson Roof

- pull monitoring out of electron app
- still accessible through separate domain AND in cosmos-ui

**Comment by nylira** [comment]
@mappum I'm trying to get the network monitor working with `tak`. I can get the main network details to work:

<img width="1038" alt="screen shot 2017-11-13 at 8 21 01 am" src="https://user-images.githubusercontent.com/172531/32730130-b1509048-c84b-11e7-9856-bfbcde349041.png">

But the the function `getValidators` in `validators.js` doesn't seem to be returning anything usable, so the Validators page is broken:

<img width="1440" alt="screen shot 2017-11-13 at 8 21 13 am" src="https://user-images.githubusercontent.com/172531/32730159-c95ee112-c84b-11e7-96dd-2b96c407b465.png">

**Comment by jolesbi** [comment]
it was decided that we would NOT be setting up the netmon outside of the UI pre-launch.

**Comment by jolesbi** [comment]
@nylira @mappum @faboweb 

can someone speak to the status of netmon right now? does it work? should it work? do we know the issue? is it smart enough to work with whichever network the ui is running on?

**Comment by jolesbi** [comment]
component is built somewhere in git history but no data yet. used to use polling for data but should be set up with sockets.

this includes both the dashboard style network statistics monitor & the block explorer. 

@mappum @faboweb @nylira

**Comment by jolesbi** [comment]
> User is able to see the node up time for every node in the network for last [day, week, month, year?]

i don't think this info is particularly important as part of the netmon. this is info that should matter for a validator / candidate. i'd propose to cross this off the list above.

> User is able to see the amount of currently active node?

i'd propose this be moved to the footer. 

---

i'd like to propose that we switch the word in the sidebar from 'Monitor' to 'Blocks'. this page will then show a list of blocks, each one clickable, taking the user to the `PageBlock` for that block. 

i'd also like to move the following to a native About section. arguably, we don't need to share the ABCI version, and we should add the UI version and the gaia / hub version if we are going to include Tendermint. the network name is already in the footer.
```
Network Name
gaia-2-dev
ABCI Version
0.7.1
Tendermint Version
0.13.0
```

**Comment by jolesbi** [comment]
as discussed in team meeting today...

- netmon is marketing feature that will wait until after launch
- switch "Monitor" to "Blocks"
- remove Version numbers 

see #344 for details about block explorer
