### ISSUE TITLE
Error when clicking on delegate v. 0.3.0 mac

### ISSUE THREAD

**Issue by valuead** [cosmos/cosmos-ui#308]
Clicking on Delegates gives you an error 
fresh install balance 0 
no history 

Additional connectivity has no information 

![screen shot 2018-01-03 at 1 03 07 am](https://user-images.githubusercontent.com/9205462/34503616-ff21b9c0-f021-11e7-9000-6c9ba2ae26bd.png)

**Comment by jolesbi** [comment]
thanks for the ticket @valuead!i believe what you've reported is covered by #290.

**Comment by valuead** [comment]
how would I share, please advise

**Comment by jolesbi** [comment]
i'm sorry. i misunderstood... 

the error you've encountered will be resolved by the fix for #290. you can refresh the app `cmd + r`, or log out and log in again. this should fix the probably in the mean time. please let us know if it works.

**Comment by mappum** [comment]
@valuead Do the delegates show up when you press the refresh button on the top right?
