### ISSUE TITLE
Balance state not shown at startup

### ISSUE THREAD

**Issue by mappum** [cosmos/cosmos-ui#32]
Had to switch to another page then switch back to update the balances.

**Comment by faboweb** [comment]
can't reproduce anymore

**Comment by faboweb** [comment]
As mentioned by Matt this may not be fixed.

**Comment by jolesbi** [comment]
for me, the balance shows 0 for 1 second before updating to the actual balance. ideally, the user would see a loading icon until the actual balance was available.

**Comment by mappum** [comment]
Can't reproduce this anymore after our recent changes.
