### ISSUE TITLE
Improve UX if user has no coins on send-page

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#321]
Currently it shows the option to select a denom. But there are no denoms available.

![image](https://user-images.githubusercontent.com/5869273/34559137-0909813c-f141-11e7-8340-d64b6b54c208.png)

**Comment by jolesbi** [comment]
this is already solved by removing "send" from the sidebar and having users visit the send page (or modal) via a button on balance.

see #317
