### ISSUE TITLE
Bonding UI improvements

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-ui#332]
@jolesbi brought up the idea of alternate input methods for bonding. I've been thinking about for quite some time. I've come up with the idea of sliders as the primary input method for bonding. I made a concept in sketch:

![sliders](https://user-images.githubusercontent.com/172531/34660261-312239b6-f484-11e7-9df9-9b01c4994f5e.png)

Sliders is an intuitive way of splitting up resources between multiple competing options. It makes more sense and it's way easier to visualize than simply entering in numbers.

I have an idea for how to show unbonding and a previous bond "diff" too, like with git. I'll work on this sketch tomorrow.

- [x] recreate the sketch mockup in html/css
- [x] investigate dragging library for the slider
- [x] implement dragging library wtih html/css mockup
- [x] make the bar slide from 0% to 100% with an offsetWidth equal to scrubber width
- [x] set up reactive variables for the percent and absolute atoms changed
- [x] make sure setting atom allocations with the input[type=number] affects the slider
- [x] make sure atom allocation works with this new interface
- [x] implement a red bar for reducing atom allocation
- [x] implement a green bar for increasing atom allocation
- [x] implement a yellow bar for unbonding atoms
- [x] implement field validation so that user cannot go below 0 unbonded atoms
- [x] checkbox for confirmation
- [x] attempting to unbond & bond in the same transaction should not result in the "Unbonded Atoms" bar increasing in size, unbonding atoms should go into the "Unbonding..." bar
- [x] update unit tests

**Comment by nylira** [comment]
An improvement proposal that builds on #331

**Comment by jolesbi** [comment]
this looks really nice. looking forward to seeing your idea for unbonding as well.

**Comment by nylira** [comment]
## initial state
![1-initial](https://user-images.githubusercontent.com/172531/34755980-07eed346-f60b-11e7-9739-9fc3ff2bd32b.png)
## edit delegation
![2-edit](https://user-images.githubusercontent.com/172531/34755982-0837f9a4-f60b-11e7-9520-db80dbeae789.png)
## after edit
![3-current](https://user-images.githubusercontent.com/172531/34755983-086e4b80-f60b-11e7-8067-d8b8c6d43a21.png)

**Comment by faboweb** [comment]
I really like it. Cool idea with the unbonding row!
One thing (personal taste): The straight line for the green "add bonding atoms" doesn't fit well in the other rounded borders.

**Comment by jolesbi** [comment]
this is 💯 !! well done peng. please let me merge #331 before we start implementing this.

**Comment by nylira** [comment]
@jolesbi @faboweb thanks guys! Yes, let's merge #331 in first and do this on the next sprint.

**Comment by jolesbi** [comment]
i'd like to propose that we add some kind of checkbox or alert before the user submits the form since a 30 day lockup period is substantial. maybe both a checkbox and an alert? i'll leave it to you @nylira

**Comment by nylira** [comment]
@jolesbi yeah we should add a checkbox for confirmation. It's a big deal.

**Comment by jolesbi** [comment]
closed by #331
