### ISSUE TITLE
Automatic local node discovery

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/cosmos-ui#335]
It would be ideal if the UI detects whether a gaia node is running already and then just connects to that node locally.

It would make the tendermint devs life way easier :-)

**Comment by jolesbi** [comment]
automatically connecting to a local node doesn't make sense to me if all of our users are going to be running local nodes in the background after the app is up and running with the light client.

for reference: https://allinbits.slack.com/archives/C564C4P1U/p1510946010000117?thread_ts=1510859626.000247&cid=C564C4P1U

**Comment by jolesbi** [comment]
@adrianbrink we discussed in the UI meeting and we're not going to implement this in the GUI for the following reasons.

- connecting automatically can interfere with running different versions of tm / gaia / ui
- some UI clients will be running full nodes in the background
- running locally, user can use `COSMOS_NODE`
