### ISSUE TITLE
nodeIP is undefined in NiConnectivity

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#336]

**Comment by faboweb** [comment]
Could you give a little more detail? Could you maybe add the console output?

**Comment by jolesbi** [comment]
yep! no console output. the footer used to display the `nodeIP` on the right side.

in NiConnectivity.vue:
```
list-item(icon="settings_ethernet" :title="nodeIP")
```
<img width="1188" alt="screen shot 2018-01-08 at 8 48 42 pm" src="https://user-images.githubusercontent.com/6021933/34701289-5c8e5824-f4b5-11e7-87c2-0e3f8ccfddc3.png">

**Comment by faboweb** [comment]
Thx!
