### ISSUE TITLE
updates to transaction history

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#338]
- [x] add wordings "sent" and "received" to line item
- [ ] link to transaction details / PageBlock for each transaction
- [x] on Coinbase sent transactions are grey / white, not red — this makes sense to me
- [ ] ~consider adding column titles~
- [x]  standard time / date stamp

**Comment by faboweb** [comment]
We can not link to transaction directly since we don't have a UID per transaction: https://github.com/cosmos/cosmos-sdk/issues/318 . But we can link to the block.

**Comment by jolesbi** [comment]
ok cool. thanks for sharing. would you expect the data from tx/uid to be different than what’s in the block? aside from it not being specific to the UID of course...

**Comment by faboweb** [comment]
Maybe it doesn't matter. But if there are 1000 transactions in a block it could get hard to find the tx. :)

**Comment by jolesbi** [comment]
since this is historical, i don't think sorting columns makes sense here. i revoke my initial suggestion in favour of search.

**Comment by jolesbi** [comment]
closing this is because of PR #441 and because #219 covers the above unchecked boxes.
