### ISSUE TITLE
Improve UX for sending

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#346]
As the menu item for sending is gone a user has to click on a denom on the balances page to send coins. But the action is not clear. It doesn't state "send" or sth. similar. It just has an arrow that indicates actionability. I was lost there for a moment and propose we quickly add the "Send" button.

- [x] add send button to `ni-li` component for balances

![image](https://user-images.githubusercontent.com/5869273/34776257-83573c02-f616-11e7-97b7-9767b228db42.png)

**Comment by jolesbi** [comment]
absolutely! let's add a button as an option on the `ni-li` component
