### ISSUE TITLE
Enable menu bar

### ISSUE THREAD

**Issue by mappum** [cosmos/cosmos-ui#348]
The menubar was removed, but it would be nice to have (on mac at least), could potentially keep it disabled on Windows.

- [ ] add native menu bar back for MacOS and possibly Windows
- [ ] add relevant version info in new native menu area

**Comment by nylira** [comment]
Is it currently removed for binary builds? Because I'm seeing the menu bars on `yarn testnet` on latest develop.

<img width="559" alt="screen shot 2018-01-25 at 2 14 14 pm" src="https://user-images.githubusercontent.com/172531/35373588-1c42feb4-01da-11e8-883f-b2d68737616e.png">

**Comment by faboweb** [comment]
Not on windows:
![image](https://user-images.githubusercontent.com/5869273/35396456-233dfad0-01ed-11e8-8798-cb0d1a38cd7f.png)
