### ISSUE TITLE
error subscribing to headers on `yarn testnet`

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-ui#352]
<img width="534" alt="screen shot 2018-01-12 at 11 30 05 am" src="https://user-images.githubusercontent.com/172531/34857052-204d0dae-f78c-11e7-86a4-83dedcb293f5.png">

* [ ] Resolve the error

**Comment by nylira** [comment]
This is where the error is logged from:

https://github.com/cosmos/cosmos-ui/blob/develop/app/src/renderer/vuex/modules/node.js#L60

**Comment by jolesbi** [comment]
this is a known issue.

#226 was blocked by https://github.com/tendermint/tendermint/issues/1099

but apparently this is resolved here https://github.com/tendermint/tendermint/issues/1100

**Comment by jolesbi** [comment]
this shouldn't be an issue anymore since we updated / fixed RPC subscription in node.js
