### ISSUE TITLE
missing explicit keys for `li-transaction`

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-ui#353]
<img width="534" alt="screen shot 2018-01-12 at 11 32 41 am" src="https://user-images.githubusercontent.com/172531/34857089-50d8cf8a-f78c-11e7-9066-7df2af764037.png">

- [x] Resolve the warning

**Comment by faboweb** [comment]
i.time is the block time of the transaction I think. That would mean, that all transactions of one block will have the same id, which will raise an error. If I am wrong let's reclose the ticket.

**Comment by jolesbi** [comment]
@faboweb good catch. i believe you are correct. apologies. 

@nylira
