### ISSUE TITLE
Select default account on startup

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-ui#361]
If the user only has one account, the Sign In page should default to it, instead of making the user click an extra time.

If the user has multiple accounts, the Sign In page should default to the account the user used last time.

It'll help reduce sign in friction. And it'll stop making me have to sign in every time I reload the app!

Relevant screenshot:

<img width="577" alt="screen shot 2018-01-12 at 2 54 30 pm" src="https://user-images.githubusercontent.com/172531/34861488-ae490e52-f7a8-11e7-8ef9-d230503d334f.png">

- [x] if the user has one account, select it by default
- [x] focus the password field instead of the account field
- [x] if user has multiple accounts, set default account to last logged in account

**Comment by faboweb** [comment]
Good point! Let's do it. One thing to clarify: It will not completely avoid signing in every time, right? :/
