### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by nylira** [cosmos/cosmos-ui#373]
I get these warnings every time I run `yarn testnet`.

<img width="578" alt="screen shot 2018-01-17 at 11 08 30 am" src="https://user-images.githubusercontent.com/172531/35023705-c64ca73a-fb76-11e7-8bdf-3d225845b52a.png">

**Comment by jolesbi** [comment]
me too.

**Comment by faboweb** [comment]
Those where introduces when I switched to only use one source of node_modules. Thank you for opening the issue!

**Comment by faboweb** [comment]
This is an old dependency in js-tendermint@2.0.3. Let's wait for Matt to fix it.

**Comment by jolesbi** [comment]
this is resolved on my machine. can you guys confirm?

**Comment by mappum** [comment]
It's resolved for me too. Did the downstream dependency update to fix this?
