### ISSUE TITLE
purple bar on delegates page is unhelpful / broken / something's off

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#383]
i don't understand this bar. 

it looks cool but what is it supposed to show?

it looks like 85 = 100%??

maybe the math is just off?

idk 😆 

<img width="328" alt="screen shot 2018-01-22 at 3 39 56 pm" src="https://user-images.githubusercontent.com/6021933/35243434-dc06773c-ff8a-11e7-90db-2570a930a508.png">

**Comment by nylira** [comment]
The bar is ratio based. That's why 85 votes look like it's roughly double in size compared to 42 votes.

**Comment by jolesbi** [comment]
ok i guess that makes sense. i find it a bit confusing. it's another piece of information but isn't the # of votes OR the %.

do we need it?

**Comment by faboweb** [comment]
I like the visualization. If not it would look more boring. A proposal: we move the bars to the percentage column?

**Comment by nylira** [comment]
I vote for leaving it as is. I'll work on improving the overall design of LiDelegate with #390
