### ISSUE TITLE
release 0.4.0

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#389]
- [ ] make sure build for linux works
- [ ] make sure build for macos works
- [ ] make sure build for windows works
- [x] update version to 0.4.0

**Comment by TejasQ** [comment]
How is this an issue?

**Comment by faboweb** [comment]
This is a "task". We use GitHub as project management and everything should be assigned remembered and assigned to a person.

**Comment by mappum** [comment]
Released! https://github.com/cosmos/cosmos-ui/releases/tag/0.4.0
