### ISSUE TITLE
combine validators and delegates

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#390]
- [x] remove validators index in favour of delegates index
- [x] rename "delegates" in sidebar to "validators"
- [x] add differentiator for validators in index (background color for eg.)
- [x] make sure candidate profile and validator profile are the same component (with flag for candidates and validators!)

**Comment by faboweb** [comment]
Notes:
- maybe colored background
- maybe line when sorted by position (could cause trouble when sorting differs)
- maybe column/icon indicating whether validator or delegate
