### ISSUE TITLE
Use only one source for node_modules

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#47]
We have node_modules in root and in app/. This creates overhead while installing and is unpractically for testing as testing is done from root.

**Comment by faboweb** [comment]
This was more work then expected. I will defer that to a later time.

**Comment by jolesbi** [comment]
since @jaekwon and @Greg-Szabo were discussing deterministic builds and human audit-able dependencies — this ticket might be worth doing — for the sake of simplicity?

**Comment by faboweb** [comment]
We can take it into the next sprint. This should be easier now as everything is a lot more stable.
