### ISSUE TITLE
Welcome Screen

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#54]
As a user
I want to manually select to create a new account or restore an existing one
So that I feel secure about which account I am interacting with

AC
- [ ] User has the ability at first start to create a new account
- [ ] User has the ability at first start to restore an account with a fundraiser mnemonic

**Comment by faboweb** [comment]
It may also be valuable to choose your own private_key instead of generating one.

**Comment by jolesbi** [comment]
@faboweb @nylira @mappum 

@ebuchman has asked we support 4 ways to access the cosmos-ui.

1. create new account / generate new key (w optional mnemonic)
2. log in with hardware / ledger wallet
3. log in with mnemonic (from fundraiser)
4. log in with local keystore / JSON file

i guess if we are supporting mnemonics — we need to allow people to change them / set them in their settings, right?
