### ISSUE TITLE
The process is not quitting if the electron window gets closed

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#62]

**Comment by faboweb** [comment]
In development `webpack-dev-server` does not terminate on kill command leaving the port blocked.

**Comment by jolesbi** [comment]
this is done.

**Comment by faboweb** [comment]
Did u test this? @jolesbi

**Comment by jolesbi** [comment]
this is still an issue for me sometimes...

```
gaia: ERROR: listen tcp :8998: bind: address already in use
```

**Comment by jolesbi** [comment]
@faboweb i think this was because i was trying to run cosmos locally while i had the dmg running. is this is an issue? if not, just close again. 😄

**Comment by faboweb** [comment]
Yes it is. The port is hardcoded. We could make it dynamic. It is a rare case, that the user runs the installed app and the dev app. But there could be other software blocking the port.

**Comment by faboweb** [comment]
Additionally we could make the production port different then the dev port.
