### ISSUE TITLE
Back-button behaviour

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#70]
The back button behavior is not consistent in the application. Sometimes it is there, sometimes it isn't. It also does not work like expected (going back to the last view) in some cases.

**Comment by faboweb** [comment]
Decided on go back in page history.

**Comment by jolesbi** [comment]
requires further thought / discussion @nylira

**Comment by nylira** [comment]
Go back in page history works for me. The sidebar lets you go anywhere else the user may want to. @jolesbi?

**Comment by nylira** [comment]
I've been thinking about this and I think it's best to just remove the back button. This app is not a web browser, and shouldn't have the concept of going back a page. Having no back button will also force us to evaluate the rest of the app navigation to make sure it functions well with hierarchical navigation.

**Comment by faboweb** [comment]
Counter proposal (leave as is :)):
Right now we have a back-button on level 2 hierarchy views i.e. Candidates / Candidate. This is also the use-case for going back (no context switch). We could try to limit ourselves to those 2 levels of hierarchy (as is right now I believe).
Use-case where this is necessary: Mobile-view (where there is no side menu) -> Switching between candidates / transactions

But I am open to alternative concepts

**Comment by nylira** [comment]
Thumbs up for leave as-is. It's making more sense with the desktop header navigation.
