### ISSUE TITLE
Mock transactions

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#74]
Child of: #22 

As long as we don't have data from the block-chain, all possible view elements should be viewable so we can start testing early with users.

For the transactions it shows an empty list for. We should mock this.

Add: We should show something like "No transactions for selected account". If there are none.

**Comment by nylira** [comment]
I'm on it.

**Comment by nylira** [comment]
Resolved in #86

**Comment by jolesbi** [comment]
@nylira ideally we would have messages / notifications for every component when there is no data so the app never feels broken.

like instead of the validators list being empty, it would say "Uh Oh! There are no validators on this network!" etc... etc...
