### ISSUE TITLE
Remove Delegators View Update

### ISSUE THREAD

**Issue by faboweb** [cosmos/cosmos-ui#79]
Child of: #24 

Do we still need a filter for on-/offline delegators?

**Comment by mappum** [comment]
IMO we don't need the Delegators view, it would just end up being a list of thousands of pseudonymous accounts. It won't really be meaningful since there will be so many delegators, similar to making a view of every account balance for the whole chain.

**Comment by faboweb** [comment]
Then let's remove it. What do you think @nylira @jolesbi ?

**Comment by nylira** [comment]
Let's remove it.

**Comment by nylira** [comment]
I'll work on this right now.
