### ISSUE TITLE
instead of having to delete /.cosmos-ui[-dev] all the time

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#95]
we discussed having separate folders for each network to avoid conflicts (and frustration)

**Comment by jolesbi** [comment]
@faboweb @mappum do we still want to implement this?

**Comment by mappum** [comment]
Yes, I think this will make a lot of sense for when we support multiple
networks. Although it's not as much of a priority right now since we
haven't been breaking things by switching networks

**Comment by faboweb** [comment]
Closing this in favor of opening a new ticket when we implement multiple networks.
