### ISSUE TITLE
no data states need to be informative and communicative

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos-ui#97]
every route / feature should have messaging when data is not present.

for example, if netmon is down — it should say... 

"Sorry, even though you're running / connected to a full node we can't get display this data for you right now — try again later or contact us to let us know" 

... or some such message. A nice little graphic too would go a long way.

**Comment by nylira** [comment]
Agreed, something showing lack of data is super useful and makes the app feel less buggy.
